baseURL = "https://ca.shoogle.net/ontario/"
languageCode = "en-US"
title = "Ontario"
theme = "ln-base"

disableKinds = ["RSS", "robotsTXT"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "ontario"

[taxonomies]
  shop = "shops"

